version: "3.9"
services:
  db:
    image: postgres:latest  # Используй образ PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"  # Открой порт для доступа извне (только для разработки)
    volumes:
      - db_data:/var/lib/postgresql/data  # Сохраняй данные между перезапусками

  bot:
    build: .
    image: house  # Имя твоего образа бота
    restart: always
    environment:
      ACCESS_KEY: "your_access_key"
      SECRET_KEY: "your_secret_key"
      BUCKET_NAME: "your_bucket_name"
      DATABASE_URL: "postgresql://your_user:your_password@db:5432/your_db" # URL для подключения к БД
    depends_on:
      - db  # Бот зависит от базы данных

volumes:
  db_data: